name: ci
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Debug Repository Info
        run: |
          echo "Repository Name: ${{ github.repository }}"
          echo "Repository Owner: ${{ github.repository_owner }}"
          echo "Repository Branch: ${{ github.ref }}"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::711387141889:role/GitHubActionsDeployRole
          aws-region: us-east-1
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build image 
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_NAME: webapp
        run:
          docker build -t $IMAGE_NAME .

      - name: Trivy image scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: $IMAGE_NAME:latest
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exitcode: 1
          ignore-unfixed: false
          output: 'trivy-results.txt'

      - name: Push image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_NAME: webapp
        run:
          docker tag $IMAGE_NAME:latest $ECR_REGISTRY/$IMAGE_NAME:latest
          docker push $ECR_REGISTRY/$IMAGE_NAME:latest
      - name: update config to conect to EKS
        run: |
          aws eks update-kubeconfig \
          --name eks-project-dev-eks-cluster \
          --region eu-north-1
        
      - name: Deploy to EKS
        run: |
         kubectl apply -f webapp/deployment.yaml
        


        